/**
 * dApp identification for script addresses and mint policies, from the bundled CRFA
 * off-chain data registry snapshot (`dapps.json`, regenerated by
 * `scripts/build-dapps.mjs`).
 *
 * Beyond the project name, each entry carries the registry's `category`/`subCategory`
 * and a canonical `role` folded from the script's name — that role is what lets a tx
 * read as an action rather than a transfer: an output to Minswap's "Batch Order" script
 * is an order, an output to its "Liquidity Pool" script is not.
 */
import registry from './dapps.json';
import { paymentCredential, stakeCredential } from './bech32';

/** What a script is for. See `ROLES` in `scripts/build-dapps.mjs` for the mapping. */
export type DappRole =
  | 'order'
  | 'pool'
  | 'deposit'
  | 'redeem'
  | 'farm'
  | 'stake'
  | 'lend'
  | 'vault'
  | 'market'
  | 'vesting'
  | 'oracle'
  | 'launchpad'
  | 'governance';

export interface Dapp {
  /** Project name as the registry spells it, e.g. "Minswap", "jpg.store". */
  name: string;
  /** Registry category, e.g. "DEFI", "MARKETPLACE", "COLLECTION". */
  category: string | null;
  /** Registry subCategory, e.g. "AMM_DEX", "LENDING_BORROWING", "NFT". */
  sub: string | null;
  /** What this particular script does; null when the registry doesn't name it. */
  role: DappRole | null;
}

interface RegistryFile {
  apps: { name: string; category: string | null; sub: string | null }[];
  roles: string[];
  /** `[appIndex]` or `[appIndex, roleIndex]`. */
  addr: Record<string, number[]>;
  /** Script hash (28-byte hex) → entry, from protocols that publish their own. */
  hash: Record<string, number[]>;
  policy: Record<string, number[]>;
}

const data = registry as RegistryFile;

function resolve(entry: number[] | undefined): Dapp | undefined {
  if (!entry) return undefined;
  const app = data.apps[entry[0]];
  if (!app) return undefined;
  const role = entry.length > 1 ? (data.roles[entry[1]] as DappRole) : null;
  return { name: app.name, category: app.category, sub: app.sub, role: role ?? null };
}

/**
 * Registry entries indexed by a credential of their address, `null` where two dApps
 * share one. Built on first use rather than at import: almost every lookup is an exact
 * hit, and decoding 1,600 bech32 addresses shouldn't sit on the first render.
 */
type CredIndex = Map<string, number[] | null>;
let byPayCred: CredIndex | null = null;
let byStakeCred: CredIndex | null = null;

function indexBy(credential: (address: string) => string | null): CredIndex {
  const index: CredIndex = new Map();
  for (const [address, entry] of Object.entries(data.addr)) {
    const cred = credential(address);
    if (cred === null) continue;
    if (!index.has(cred)) {
      index.set(cred, entry);
      continue;
    }
    const seen = index.get(cred)!;
    if (seen === null || seen[0] === entry[0]) {
      // Same dApp under two roles — keep the dApp, drop the role it can't decide.
      if (seen !== null && seen[1] !== entry[1]) index.set(cred, [entry[0]]);
    } else {
      index.set(cred, null); // two dApps: the credential doesn't identify either
    }
  }
  return index;
}

/**
 * The dApp owning `address`, if it's a known script.
 *
 * The registry lists exact addresses, which under-matches badly: the same script is
 * deployed both as a bare script address and as one with a staking part, and the
 * registry usually lists only one of the two. So fall back to the script hash, then —
 * because a dApp stakes all its script UTXOs to one credential — to the staking part.
 * That last match identifies the project but not which of its contracts, so it comes
 * back without a role rather than borrowing an unrelated one.
 */
export function dappForAddress(address: string): Dapp | undefined {
  const exact = data.addr[address];
  if (exact) return resolve(exact);

  // A hash a protocol published itself identifies the script under every address form
  // it's deployed at, so it comes before anything derived from an address list.
  const declared = data.hash[paymentCredential(address) ?? ''];
  if (declared) return resolve(declared);

  byPayCred ??= indexBy(paymentCredential);
  const sameScript = byPayCred.get(paymentCredential(address) ?? '');
  if (sameScript) return resolve(sameScript);

  byStakeCred ??= indexBy(stakeCredential);
  const sameProject = byStakeCred.get(stakeCredential(address) ?? '');
  return sameProject ? resolve([sameProject[0]]) : undefined;
}

/** The dApp owning `policy` (hex), if it's a known mint policy. */
export function dappForPolicy(policy: string): Dapp | undefined {
  return resolve(data.policy[policy]);
}

/** Every project name in the registry — the vocabulary a dApp naming itself in a tx
 *  message is matched against. See `cip20.ts`. */
export function registryAppNames(): string[] {
  return data.apps.map((a) => a.name);
}

/** Any exchange — AMM, order book, aggregator, concentrated liquidity. */
export function isDex(dapp: Dapp): boolean {
  return dapp.sub !== null && dapp.sub.includes('DEX');
}
