/**
 * dApp identification for script addresses and mint policies, from the bundled CRFA
 * off-chain data registry snapshot (`dapps.json`, regenerated by
 * `scripts/build-dapps.mjs`).
 *
 * Beyond the project name, each entry carries the registry's `category`/`subCategory`
 * and a canonical `role` folded from the script's name — that role is what lets a tx
 * read as an action rather than a transfer: an output to Minswap's "Batch Order" script
 * is an order, an output to its "Liquidity Pool" script is not.
 */
import registry from './dapps.json';

/** What a script is for. See `ROLES` in `scripts/build-dapps.mjs` for the mapping. */
export type DappRole =
  | 'order'
  | 'pool'
  | 'deposit'
  | 'redeem'
  | 'farm'
  | 'stake'
  | 'lend'
  | 'vault'
  | 'market'
  | 'vesting'
  | 'oracle'
  | 'launchpad'
  | 'governance';

export interface Dapp {
  /** Project name as the registry spells it, e.g. "Minswap", "jpg.store". */
  name: string;
  /** Registry category, e.g. "DEFI", "MARKETPLACE", "COLLECTION". */
  category: string | null;
  /** Registry subCategory, e.g. "AMM_DEX", "LENDING_BORROWING", "NFT". */
  sub: string | null;
  /** What this particular script does; null when the registry doesn't name it. */
  role: DappRole | null;
}

interface RegistryFile {
  apps: { name: string; category: string | null; sub: string | null }[];
  roles: string[];
  /** `[appIndex]` or `[appIndex, roleIndex]`. */
  addr: Record<string, number[]>;
  policy: Record<string, number[]>;
}

const data = registry as RegistryFile;

function resolve(entry: number[] | undefined): Dapp | undefined {
  if (!entry) return undefined;
  const app = data.apps[entry[0]];
  if (!app) return undefined;
  const role = entry.length > 1 ? (data.roles[entry[1]] as DappRole) : null;
  return { name: app.name, category: app.category, sub: app.sub, role: role ?? null };
}

/** The dApp owning `address`, if it's a known script address. */
export function dappForAddress(address: string): Dapp | undefined {
  return resolve(data.addr[address]);
}

/** The dApp owning `policy` (hex), if it's a known mint policy. */
export function dappForPolicy(policy: string): Dapp | undefined {
  return resolve(data.policy[policy]);
}

/** Any exchange — AMM, order book, aggregator, concentrated liquidity. */
export function isDex(dapp: Dapp): boolean {
  return dapp.sub !== null && dapp.sub.includes('DEX');
}
