/**
 * Resolve a Minswap V2 pool to the two assets it trades.
 *
 * A Minswap order datum names its pool by the pool's LP token, never by the pair:
 *
 *     lp_asset.name = sha3_256( sha3_256(policyA ++ nameA) ++ sha3_256(policyB ++ nameB) )
 *
 * That's a digest, so it can't be inverted — hence the bundled table, regenerated by
 * `scripts/build-minswap-pools.mjs`, which verifies every entry against that hash before
 * shipping it. Only V2 pools are covered; V1 and the stableswap pools derive their LP
 * names differently and their orders use a different script and datum.
 */
import table from './minswap-pools.json';

/** One side of a pool: the asset's on-chain identity, which is all that's stored. */
export interface PoolAsset {
  /** Policy id (hex). Empty for ADA. */
  policy: string;
  /** Asset name (hex). Empty for ADA. */
  name: string;
}

interface PoolTable {
  /** Minswap V2's LP policy — checked before trusting a name lookup. */
  policy: string;
  /** `[policy, name]` per asset, interned: ADA is one side of nearly every pool. */
  assets: string[][];
  /** LP token name → the pair's two asset indices, in hash order. */
  pools: Record<string, number[]>;
}

const data = table as PoolTable;

/** ADA is `("", "")` on chain, and has no policy or name to look up. */
export function isAda(asset: PoolAsset): boolean {
  return asset.policy === '' && asset.name === '';
}

/**
 * The pool's `[assetA, assetB]`, in the order the LP name was hashed in — which is the
 * order the order datum's `direction` field selects between, so it must not be reordered.
 *
 * `policy` is the datum's own `lp_asset` policy; a token minted under anything else isn't
 * a V2 LP token and gets no answer, however its name might collide.
 */
export function poolPair(policy: string, name: string): [PoolAsset, PoolAsset] | undefined {
  if (policy !== data.policy) return undefined;
  const pair = data.pools[name];
  if (pair?.length !== 2) return undefined;
  const a = asset(pair[0]);
  const b = asset(pair[1]);
  return a && b ? [a, b] : undefined;
}

function asset(index: number): PoolAsset | undefined {
  const entry = data.assets[index];
  return entry ? { policy: entry[0], name: entry[1] } : undefined;
}
